version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
      - ./scripts:/app/scripts
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Optional Redis service for task queue (e.g., for retraining tasks)
  redis:
    image: "redis:latest"
    expose:
      - "6379"
    restart: always
